# AK 2026 Soil Data Bank Grant - Meeting Agenda - Friday, August 11th (9am AK, 11AM Mountain, 1PM Eastern)

Hi Everyone -

Apologies for the cancellation of our June meeting, and July flew by in the field - I know most people have been traveling and out. I am currently between fieldwork but would like to hold a short check-in during our normal scheduled time this Friday, August 11th (Zoom link below if you don't have it). I know many folks may not be able to attend, but if you are able please do and we can make it short.

I am including Dave D'Amore and Jacquie Foss (USFS) as well as Timm Nawrocki (Alaska Center for Conservation Science) as I would like to give the three of them visibility over our work in the context of this project as they will be contributing data and potentially be co-authors in the future. Dave, Jacquie and Timm - please feel free to join if you are able - if not, no worries - full meetings will resume monthly in September (second Friday of each month) and we would love to have you join as you are able.

The main points of discussion I would like to address are updates on data curation, GEMS, and general check-ins/setting the objectives for the fall.

Time (Friday, 8/11): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf)
1PM Eastern (Sabine)

Agenda:
1. Check-In and Introductions (if anyone new joins)
2. Updates on Action Items from May/June
2. Update/review/discussion re: data curation and acquisition from NPS, BLM, USFS, DOE
3. GEMS updates.
4. Broad SEP-DEC objectives
5. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 August Team Meeting
Time: August 11, 2023 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic
--