# AK 2026 SPSD ASDB Grant - Meeting #5 Agenda - Friday, March 10th [09MAR2023]

Hi Everyone -

Just a reminder that our March AKSDB project meeting is tomorrow, Friday, March 10th. 

I would like to keep the agenda items fairly similar to last time (since we were missing both Sabine and Colby), with the caveat that we have made progress on some of these and I will be providing updates in addition to discussion.

**Time (Friday, 3/10):**
9AM AK (Matt & Sue & Mike)
11AM Mountain (Colby)
12PM Central (Nic)
1PM Eastern (Sabine)

**Agenda:**
1. Updates on Action Items from previous meeting ~10 min
2. Update/review/discussion re: data sharing agreements/memoranda of understanding
3. Preliminary discussion regarding authorship guidelines and considerations
4. Any other discussion or related business - time remaining

**Zoom Link (in case you don't have it):**
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 Grant Team Meeting #4
Time: Mar 10, 2023 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic