# [AKSDB] Agenda: February Meeting Friday (2/9) : 9AM AK, 11AM Mountain, 12PM CST, 1PM Eastern)

Hi Everyone -

A reminder that we will be holding our monthly project check-in during our normal scheduled time tomorrow, Friday, February 9th (Zoom link below if you don't have it). Our first order of business will be January action item updates, followed by data curation/acquisition updates. 

After those standard items, I would like to use our time to continue to discuss and brainstorm potential science products, follow-on work, and potential follow-on funding. I owe Neal P (USGS) for prompting this, as a conversation we had in December sparked some very intriguing ideas for future products resulting from the data we are compiling.

NOTE: The 2024 Pedometrics conference is taking place this week and it will be difficult for a few of our members (Colby B., Sabine G., Irf A.) to join. Nevertheless, I would like to continue with our normal schedule and will record/take notes so that those who can't join can review our discussion.

Time (Friday, 2/9): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf & Josh & Neal & Katrina)
1PM Eastern (Sabine, Erin)

Agenda:
1. Updates on Action Items from January
2. Update/review/discussion re: data curation and acquisition progress
3. Discussion re: potential science questions and products, and follow-on planning/funding
4. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 February Team Meeting
Time: February 9, 2024 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic
--