# [AKSDB - Action Item for September] Review Data Sharing and Use and Co-Authorship Guidelines Draft Documents [11AUG2023]

Hi Everyone -

Irfan, Sabine and I had a very productive discussion today with our USFS colleagues Dave D'Amore, Frances Biles and Jacquie Foss, who will be joining our group and meetings as they are able. I will post meeting minutes to the GitHub site, however there is one action item I am requesting prior to our September 8th meeting:

Please review and provide any comments as you are able on 1) our draft data sharing and use and 2) co-authorship guidelines and agreements. Note that the data sharing agreement is targeted for the most restrictive data provider (i.e. Conoco-Phillips) - clearly many data providers will not need or require a data sharing agreement or may want to significantly pare down what is in the current draft, and that is just fine.

I am providing both draft documents here as word documents because some folks have had problems accessing Google Docs. Please feel free to make any comments you have either on the docs or in an email and send back to Irfan and I. We will consolidate.

Thank you and enjoy August!

Respectfully,
Nic
