# [AKSDB] EUCOP Poster Draft + Cancel Tomorrow's June 9th Project Meeting [08JUN2023]

Hi Everyone -

Cancel June Meeting. My sincerest apologies but due to some unanticipated fieldwork & travel I need to cancel our June project meeting (originally scheduled for tomorrow, Friday, June 9th). I'm sure many others are otherwise occupied as well. Instead, I will provide project updates by the end of the June to everyone. Current action items (in brief) are to:
1. Complete draft of data sharing agreement (Nic)
2. Complete wrangling of preliminary datasets into GEMS (Irf)
3. Continue to pursue/expand data wrangling efforts (Nic, Irf, All). In that vein, I have asked Dave D'Amore (USFS Alaska) to join our group as USFS will be contributing quite a load of data and Dave has expressed interest in participating. If anyone has objections to this please let me know.

EUCOP Poster. Finally, I will be attending EUCOP as part of another project but am presenting a poster on our project. It is more a "project overview" poster than a results poster at this point. See initial draft attached - please let me know if you would like to see any changes by Monday @ 10:00AM (I will print Monday afternoon).

Sabine: Could you send me an approved UF logo for use?
Colby: Is the NMSU logo OK?
Matt & Sue: Could you send me the current ABR logo (I think the one I put on there is old?).

Thank you all!

AKSDB Poster DRAFT Updated w Figures 08JUN2023.pdf
 
Respectfully,
Nic
