# [AKSDB] Follow Up: SEP Brief Minutes + Revised Data Sharing Agreement (v 1.2) [08SEP2023]

Hi Everyone -

Thanks for all in attendance at todays meeting. Brief minutes as follows:

1. Discussed updates on Action Items from August - I consolidated all comments on the data sharing agreement template and am attaching the current version 1.2 (dated 08SEP2023) here. Matt - please use this template as you engage on the Conoco and Hilcorp datasets - let me know if you think anything should be modified further as you begin discussions with those entities.
2. Discussed recent find of Mark Clark STATSGO pedons (~150) not in NASIS in the NRCS Wasilla office. Nic's group will work on getting these in NASIS. 
3. GEMS updates - Irf will give an update in October.
4. Oral presentation abstract for 2024 Pedometrics conference - due 15OCT. Nic will get an initial draft to this group by next Friday and request comments/edits. Everyone on this email group will be invited to be a co-author on the presentation.

Thank you all! Next meeting is Friday, October 13.

Respectfully,
Nic

