# AKSDB Initial Meeting Follow-Up and Future Meetings [18NOV2022]

Colby, Sabine, and Matt - 

I have now added minutes from our first "AKSDB" team meeting (on 24OCT) to the [Box shared folder](https://umn.box.com/s/ds39mw3e5lyj0y8oeaj9neu4sqtq8jp6).

In terms of action items from our first meeting, I believe the following things have been addressed:

1. Colby has contacted Suzann Kienast-Brown to request Matt and Sabine be added to the NRCS AK 2026 Task Force mailing list and meeting schedule (the November NRCS task force meeting was cancelled so you haven't missed anything yet).

2. I believe the NMSU and UF subawards have now gone through - Sabine - I also believe we got the start date corrected now for the UF subaward.

3. Matt - as I mentioned in my email to you today, the contract for professional services/PO paperwork for ABR is with our accounting for review. I'll be in touch as soon as I hear anything further.

4. It was suggested that we set up monthly meetings. I set up a [When2Meet](https://www.when2meet.com/?17761855-a9uMt) to try and find a 1 hr block of time to meet on either 12DEC, 13DEC, or 14DEC - I hope one of these days will work - if not I will suggest alternate dates. Please fill it out at your convenience. At our DEC meeting, we can make it an agenda item to find a recurring monthly time that works for everyone starting in January and moving forward.

My apologies that it has taken me a while to follow-up - the week after our October meeting my wife gave birth to our second boy, so I've been a bit behind but am steadily digging out!

Respectfully,
Nic