# AK 2026 SPSD AKSDB Grant - Meeting #6 Agenda - Friday, April 14th [13APR2023]

Hi Everyone -

Just a reminder that our April AKSDB project meeting is tomorrow, Friday, April 14th. 

This meeting may be a bit shorter (30-45 min) as I have a PhD defense committee to site on immediately following. The main points of discussion I would like to address are updates on data curation from various sources and also our May-August meeting schedule.

**Time (Friday, 4/14):** 
9AM AK (Matt & Sue & Mike)
11AM Mountain (Colby)
12PM Central (Nic)
1PM Eastern (Sabine)

**Agenda:**
1. Updates on Action Items from previous meeting
2. Update/review/discussion re: data curation and acquisition from NPS, BLM, USFS, DOE
3. Discussion regarding additional needs for contacting initiating data acquisition discussions from other sources.
4. Meeting schedule May-August
5. Any other discussion or related business - time remaining

**Zoom Link (in case you don't have it):**
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 Grant Team Meeting #6
Time: April 14, 2023 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic