# Reminder: AK 2026 SPSD AKSDB Grant - Meeting #2 - Wednesday, December 14th [05DEC2022]

Hi Everyone -

Apologies for the delay on getting this scheduled on my end - with a newborn in the house I'm still playing a bit of catchup. Based on the When2Meet that everyone filled out, it looks like December 14th was the best choice. Please let me know if this time no longer works for you and I will work to find an alternative. I did send out a Google Calendar invite but just to be clear because we are operating on 4 different timezones:

Time (Wednesday , 12/14): 
10AM AK (Matt)
12PM Mountain (Colby)
1PM Central (Nic)
2PM Eastern (Sabine)

Agenda:
I scheduled us for an hour, we may or may not take that whole time. I would like to suggest that we spend the "body" of the meeting discussing task specifics centered around Deliverable #1:

1. Updates on Action Items from previous meeting ~15 min
2. Agree on and schedule recurring meetings moving forward ~10min
3. Begin discussion on execution of Deliverable #1 ~30 min
4. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 Grant Team Meeting #2
Time: Dec 14, 2022 01:00 PM Central Time (10AK, 12PM Mountain, 2PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/97717859442?pwd=SGhvdGJSemxvYnVadjFFNUxRVW5DUT09

Meeting ID: 977 1785 9442
Passcode: 6GFWs8

Respectfully,
Nic