# [AKSDB] Agenda: March Meeting Friday (3/8) : 9AM AK, 11AM Mountain, 12PM CST, 1PM Eastern)

Hi Everyone -

A reminder that we will be holding our monthly project check-in during our normal scheduled time this Friday, March 8th (Zoom link below if you don't have it). Our first order of business will be February action item updates, followed by data curation/acquisition updates. 

There is quite a bit of momentum that has been building over the past 30-60 days, so I'd like to take most of our time to provide updates on data acquisition and curation status, and additionally highlight some of the preliminary WOSIS and ISCN extraction tools we have begun to build (with the end goal of providing a single dashboard and set of tools for showing any data overlap from diverse sources).
Time (Friday, 3/8): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf & Josh & Neal & Katrina)
1PM Eastern (Sabine, Erin)

Agenda:
1. Updates on Action Items from February
2. NCE Request3. Update/review/discussion re: data curation and acquisition progress 
4. Preliminary WOSIS/ISCN extraction and comparison tools - towards building a data dashboard for AK
5. Connections with Soil Informatics ESIP group (lead: Kathe Todd-Browne)6. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 March Team Meeting
Time: March 8, 2024 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9
Respectfully,Nic
--