# Reminder: AK 2026 Soil Data Bank Grant - Today - Friday, September 8th (9am AK, 11AM Mountain, 1PM Eastern) [08SEP2023]

Hi Everyone -

A reminder that we will be holding a check-in during our normal scheduled time today, Friday, September 8th (Zoom link below if you don't have it). If you are unable to attend, don't worry - I will send minutes afterwards.

Time (Friday, 9/8): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf)
1PM Eastern (Sabine)

Agenda:
1. Updates on Action Items from August - some of you have provided comments on the data sharing and co-authorship agreements (drafts attached again here) - I have consolidated comments - we will review comments and discuss for everyone in attendance.
2. Update/review/discussion re: data curation and acquisition from NPS, BLM, USFS, DOE.
3. Update on very significant recently discovered data from NRCS - not in NASIS.
3. GEMS updates.
4. Broad SEP-DEC objectives
5. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 August Team Meeting
Time: September 08, 2023 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic