# [AKSDB - Action Item] Pedometrics 2024 Conference Abstract + October Meeting (10/13) Reminder and Agenda [11OCT2023]

Hi Everyone -

Two big items:
1). Pedometrics 2024 Abstract. I am sharing a draft of a Pedometrics 2024 conference abstract (due this Sunday, 15OCT). While our previous EUCOP 2023 poster focused on the high level aspects of the project itself, this talk will focus on the workflow details and will be highly relevant to the pedometrics audience. Please take action by reading the abstract draft and making any suggestions (I know not everyone can access Google Drive so I am just attaching here as a document). Feel free to send back any comments and I will consolidate. Federal folks: I have you listed as potential co-authors - however I know some of you made need approval - if this timeline is too short for you to get approval (apologies) just let me know and we can either remove you from the co-author list or delay and edit/add you once you get approval.

2). October Monthly Meeting. A reminder that we will be holding our monthly project check-in during our normal scheduled time this Friday, October 13th (Zoom link below if you don't have it). 

Time (Friday, 10/13): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf)
1PM Eastern (Sabine)

Agenda:
1. Updates on Action Items from September
2. Pedometrics 2024 abstract
3. Update/review/discussion re: data curation and acquisition from NPS, BLM, USFS, DOE.
4. Presentation of GEMS scripting workflow
5. Potential new group members: Travis Nauman (NRCS) and Erin Rooney (NRCS) + Woodwell Climate Folks (Y-K Delta).
6. Broad OCT-DEC objectives
7. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 August Team Meeting
Time: October 13, 2023 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9


Respectfully,
Nic
