# AK 2026 SPSD ASDB Grant - Meeting #4 Action Items + Agenda - Friday, February 10th [07FEB2023]

Hi Everyone -

Just a reminder that our February AKSDB project meeting is this Friday, February 10th. Mike Sousa (USDA-NRCS Alaska may also begin joining in on some of these meetings). 

Irf and I have drafted a more complete outline of our [project metadata document which can be found here](https://alaska-soil-data-bank.github.io/project-metadata/). Most sections are incomplete, and there are potentially many other sections to add, but it is a start that we can work on. Remember that this is our project level metadata, and not dataset-level metadata, which will be managed in GEMS.

**Everyone**: If you have a chance please at least briefly scroll through the document and familiarize yourself with the structure. In the meeting we will have time to review and documents any critiques, questions or things you would like to see added.

**Sabine**: If you have any comments please feel free to send them to me directly and I will incorporate them into our notes. I am especially interested in your perspectives on authorship guidelines/data contributions. We are just starting this conversation this month, so will have plenty of other opportunities to discuss in the future.

**Time (Friday, 2/10)**: 
9AM AK (Matt & Sue & Mike)
11AM Mountain (Colby)
12PM Central (Nic)
1PM Eastern (Sabine) - Sabine will not be in attendance at this meeting

**Agenda**:
1. Updates on Action Items from previous meeting ~10 min
2. Discussion regarding draft project metadata document under development - sections to add in outline, other considerations
3. Review and discussion re: data sharing agreements/memoranda of understanding
4. Preliminary discussion regarding authorship guidelines and considerations
5. Any other discussion or related business - time remaining

**Zoom Link (in case you don't have it)**:
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 Grant Team Meeting #4
Time: Feb 10, 2023 12:00 PM Central Time (9AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic
