# [AKSDB] Reminder: January Meeting Friday (1/12) : 9AM AK, 11AM Mountain, 12PM CST, 1PM Eastern) + Agenda

Hi Everyone -

A reminder that we will be holding our monthly project check-in during our normal scheduled time on Friday, January 12th (Zoom link below if you don't have it). Our first order of business will be December action item updates, followed by data curation/acquisition updates. 

After those standard items, I would like to use our time to discuss and brainstorm potential science products, follow-on work, and potential follow-on funding. I owe Neal P (USGS) for prompting this, as a conversation we had in December sparked some very intriguing ideas for future products resulting from the data we are compiling.

Time (Friday, 1/12): 
9AM AK (Matt & Sue & Mike & Dave & Timm & Jacquie)
11AM Mountain (Colby)
12PM Central (Nic & Irf & Josh & Neal)
1PM Eastern (Sabine, Erin)

Agenda:
1. Updates on Action Items from December
2. Update/review/discussion re: data curation and acquisition progress
3. Discussion re: potential science questions and products, and follow-on planning/funding
4. Any other discussion or related business - time remaining

Zoom Link (in case you don't have it):
Nic Jelinski is inviting you to a scheduled Zoom meeting.
Topic: ASDB/AK 2026 January Team Meeting
Time: January 12, 2024 12:00 PM Central Time (9AM AK, 11AM Mountain, 1PM Eastern)

Join Zoom Meeting
https://umn.zoom.us/j/95708062752?pwd=OWx0cWswL3duYmg0eUtLZFVkd3dMUT09

Meeting ID: 957 0806 2752
Passcode: MLwpf9

Respectfully,
Nic
--