# AKSDB Team Meeting Minutes 14DEC2022

## Agenda and Minutes: 
### Updates on action items from previous meeting 
1. Add Sabine and Matt to NRCS AK 2026 Task Force Notifications/Team. - Colby contacted Suzanne K-B to request that Matt and Sabine be added. Next AK 2026 taskforce meeting is January 20th. 
2. Ensure subawards contracts are executed. ABR contract is now completed and ready for invoicing. NMSU and UFL subawards have been executed by UMN and sent to sponsored projects at each institution (Nic double checked). 
3. Schedule monthly recurring meetings – second Friday of each month (beginning January 13th) @ 9am AK, 11am Mountain, 12PM Central, 1PM Eastern. Will keep this schedule at least through May – then will re-evaluate for the field season and fall. 

### Discussion on executing Deliverable #1:  
1. *The Alaska Soil Data Bank (ASDB). We will acquire, curate, and centralize non-NRCS legacy data for the state of Alaska and stand up a database for continuing contributions on the G.E.M.S. platform of the University of Minnesota Supercomputing Institute. The ASDB will result in a harmonized dataset for use in digital soil mapping in Alaska and scripts will be written to export the data into a NASIS-readable format for ingestion.*
    - Major action items: 
      - Need to get Sabine, Matt and Colby set up as GEMS users. 
      - Nic needs to set up a new project team and workspace in GEMS – currently working with GEMS team to do this. GEMS has streamlined the user addition process now – one question that came up for partners – should we use one login per instutition? The answer is no – we should use individualized logins for every user because this is now further streamlined and can be attached to a specific Globus ID 
      - Once everyone is set up as users and our team is set up, Nic can pull everyone in to the project. I can add new users at any team once they are registered. 
  
2. General discussion regarding path forward on deliverable 1 
    - Agreed that we should move forward in January with reviewing 2 test datasets on the GEMS platform – for the January meeting, Nic will walk through data import, field metadata tagging, dataset or project metadata generation in GEMS, and scripting capabilities in the workspace. 
      - We will look at Chien-Lu's UAF pedon database and a snippet of the ABR legacy database 
    - Concurrently, we will begin drafting metadata architecture for the project. We will have should have this set prior to large scale data ingestion, and aim to have a first version of a full metadata document complete by May 2023 or before. 
Sabine will share the full metadata documentation for the Florida Soil Characterization Database.  

3. Some additional considerations for developing metadata architecture: 
      - Version control 
        - Github? Or work on GEMS platform in JSON? - that may be limited so perhaps work on GitHub in JSON? 
        - Additionally, it may be easiest for our full project metadata to be in a more easily editable form – while dataset specific metadata can utilize the GEMS metadata creation tools, which generate JSON formatted metadata. 
      - Need to draft data conventions: decide how to handle missing data, missing values, etc etc. Were variables not assesed due to the sampling protocol or actually missing? Are missing fields null or zero values, etc 
      - Dealing with different coordinate systems. 
      - Ontologies/ controlled vocabularies for field metadata – we can create a controlled vocabulary/ontology that is specific to our project for appending field metadata. Nic would work with GEMS engineers to set this up. 
4. Some additional considerations for wrangling datasets 
    - What format? Text files? Database exchange 
      - Nic’s first thought is we should work in csvs for most datasets. Although there is no restriction to file types in GEMS this would likely be the cleanest. Can look into database exchange options for the ABR database. 
    - Assigning unique IDs to all observations in datasets, checking for duplicates, etc 
      - This is something that can be done in the workspace on GEMS – we need to think about site vs horizon level data – need to link with ID (ABR uses a project ID and a plot ID.  
      - Colby has dealt with unique identifiers in combined datasets by appending the UTM coordinates to observations. 